# Build Pipeline for NuGet Packages

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: AlefCarlos/PlusUltra.Azure.Templates

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
    - README.md

jobs:
- job: Build
  pool:
    vmImage: vs2017-win2016

  steps:
  - task: GitVersion@5
    inputs:
      runtime: 'core'
      configFilePath: 'GitVersion.yml'
      
  - script: echo %Action%%BuildVersion%
    displayName: 'Set build version'
    env:
      Action: '##vso[build.updatebuildnumber]'
      BuildVersion: $(GitVersion.NuGetVersionV2)

  - task: DotNetCoreCLI@2
    displayName: 'Dotnet Build'
    inputs:
      command: 'build'
      projects: './content/PlusUltra.Microservice.sln'

  - template: nuget-nuspec.yaml@templates
    parameters:
      version: $(GitVersion.NuGetVersionV2)
      nuspec: 'PlusUltra.Microservice.nuspec'