# Build Pipeline for NuGet Packages

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
resources:
- repo: self

trigger:
- master

jobs:
- job: Build
  pool:
    vmImage: vs2017-win2016

  steps:
  - task: GitVersion@5
    inputs:
      runtime: 'core'
      configFilePath: 'GitVersion.yml'
      
  - script: echo %Action%%BuildVersion%
    displayName: 'Set build version'
    env:
      Action: '##vso[build.updatebuildnumber]'
      BuildVersion: $(GitVersion.NuGetVersionV2)

  - script: echo %Action%%BuildVersion%
    displayName: 'try get version'

  - task: DotNetCoreCLI@2
    displayName: 'Dotnet Build'
    inputs:
      command: 'build'
      projects: './content/PlusUltra.Microservice.sln'
  - task: NuGetCommand@2
    displayName: 'Pack nuspec'
    inputs:
      command: 'pack'
      buildProperties: 'version="$(BuildVersion)"'
      packagesToPack: 'PlusUltra.Microservice.nuspec'
      versioningScheme: 'off'

  - task: NuGetCommand@2
    displayName: 'Nuget push'  
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'nuget.org'
      verbosityPush: 'Normal'